# Setup
## title:     Spring Framework - ENTRY -
## tagline:   Spring Framework 入門
title:        Learning Spring Framework
tagline:      ngzm
baseurl:      "/training-java-spring-entry"
paginate:     1

# About/contact
author:
  name:       Naoki Nagazumi
  url:        https://github.com/ngzm/

# Gems
gems:
  - jekyll-paginate

# Collections
collections:
  handsons:
    output: true
  texts:
    output: true 

#Others
markdown: kramdown

# Excludes
exclude:
  - vendor
  - imagebase
